#!/usr/bin/env python3
"""Validate the HOD-selection covariance against the archived DES-Y1 To21 run.

The archived reference was generated by ``validation/demo_desy1.py``.  This
script deliberately follows that calculation's binning and selection path:
the redshift bin is a hard top-hat and ``ClusterCounts.calc_counts`` evaluates
the richness selection at the redshift-bin midpoint.  The HOD relation itself
comes from the sibling RichnessSelection repository, including its observed-
richness projection kernel when ``apply_projection=True``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from clens.lensing.cov_DeltaSigma import CovDeltaSigma
from clens.util.cluster_counts import ClusterCounts
from clens.util.parameters import CosmoParameters
from clens.util.richness_selection_adapter import make_intrinsic_relation
from clens.util.scaling_relation import PrecalculatedCountsBias
from clens.util.survey import Survey
from reproduce_covariance import (
    _bin_bsel_ls,
    _bsel_cache_key,
    _make_richness_selection_two_halo,
)


ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "validation" / "desy1_analytic_To21"
Z_BINS = ((0.20, 0.35), (0.35, 0.50), (0.50, 0.65))
LAMBDA_BINS = ((5, 10), (10, 14), (14, 20), (20, 30),
               (30, 45), (45, 60), (60, 1000))
_C21_HOD_CONFIG = json.loads(
    (ROOT / "configs" / "c21_spt_des_shear_hod.json").read_text(
        encoding="utf-8"
    )
)
HOD_PARAMETERS = _C21_HOD_CONFIG["hod_parameters"]


def _stem(zbin, lbin):
    def format_edge(value):
        value = float(value)
        return str(int(value)) if value.is_integer() else f"{value:g}"

    return "_".join(format_edge(value) for value in (*zbin, *lbin))


def _reference_block(zbin, lbin):
    stem = _stem(zbin, lbin)
    radial = np.loadtxt(REFERENCE / f"rp_hiMpc_{stem}.dat", comments="#")
    counts = np.loadtxt(REFERENCE / f"counts_{stem}.dat", comments="#")
    covariance = np.loadtxt(
        REFERENCE / f"DeltaSigma_cov_combined_{stem}.dat"
    )
    return {
        "r_hmpc": radial[:, 2],
        "counts": float(counts[0]),
        "bias": float(counts[2]),
        "covariance": covariance,
    }


def _survey(config):
    pz = config["source_pz"]
    return Survey(
        z_star_src=pz["z_star"],
        m_src=pz["m"],
        beta_src=pz["beta"],
        n_src_arcmin=config["n_src_arcmin2"],
        sigma_gamma=config["sigma_gamma"],
    )


def _covariance(config, counts, bias, zbin, lbin):
    co = CosmoParameters(**config["cosmology"])
    su = _survey(config)
    zmin, zmax = zbin
    lam_min, lam_max = lbin
    a = 1.0 / (1.0 + 0.5 * (zmin + zmax))
    cds = CovDeltaSigma(
        co=co,
        su=su,
        sr=PrecalculatedCountsBias(counts, bias),
        fsky=config["survey_area_deg2"] / 41253.0,
        survey_area_sq_deg=config["survey_area_deg2"],
    )
    # This is the exact radial range conversion used in demo_desy1.py.
    rp_mid, _, _ = cds.calc_cov(
        rp_min=0.03 / a,
        rp_max=30.0 / a,
        n_rp=15,
        zh_min=zmin,
        zh_max=zmax,
        lambda_min=lam_min,
        lambda_max=lam_max,
        diag_only=False,
    )
    # demo_desy1.py writes DeltaSigma_cov_combined = cov / h^2.
    return rp_mid, cds.cov_sum / co.h**2


def _bsel_cache_signature(config):
    payload = {
        "cosmology": config["cosmology"],
        "model": "hod",
        "parameters": HOD_PARAMETERS,
        "richness_selection_root": str(
            ROOT.parent / "github" / "RichnessSelection"
        ),
    }
    encoded = json.dumps(payload, sort_keys=True).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _load_bsel_cache(path, signature):
    if not path.is_file():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if payload.get("signature") != signature:
        return {}
    return {str(key): float(value) for key, value in payload.get("values", {}).items()}


def _save_bsel_cache(path, signature, values):
    path.write_text(
        json.dumps(
            {
                "signature": signature,
                "values": values,
            },
            indent=2,
        ),
        encoding="utf-8",
    )


def _selection_counts(config, bsel_cache):
    relation = make_intrinsic_relation(
        "hod",
        apply_projection=True,
        **HOD_PARAMETERS,
    )
    # Use the existing RichnessSelection marginalised large-scale selection
    # bias, b_sel_ls = b_eff (1 + delta_prj), while retaining the historical
    # ClusterCounts selection for the number counts and S_ij weighting.
    bsel_selection = {
        "model": "hod",
        "parameters": HOD_PARAMETERS,
        "richness_selection_root": str(
            ROOT.parent / "github" / "RichnessSelection"
        ),
    }
    two_halo = _make_richness_selection_two_halo(config, bsel_selection)
    cosmo = CosmoParameters(**config["cosmology"])
    counts = np.zeros((len(Z_BINS), len(LAMBDA_BINS)))
    bias = np.zeros_like(counts)
    for iz, zbin in enumerate(Z_BINS):
        for ilam, lbin in enumerate(LAMBDA_BINS):
            cc = ClusterCounts(cosmo_parameters=cosmo,
                               scaling_relation=relation)
            result = cc.calc_counts(
                zmin=zbin[0],
                zmax=zbin[1],
                lambda_min=lbin[0],
                lambda_max=lbin[1],
                survey_area_sq_deg=config["survey_area_deg2"],
            )
            counts[iz, ilam] = result[0]
            bias[iz, ilam] = _bin_bsel_ls(
                two_halo,
                lbin[0],
                lbin[1],
                zbin[0],
                zbin[1],
                open_bin_lob=80.0,
                cache=bsel_cache,
            )
    return counts, bias


def _ratio_summary(ratio):
    return {
        "median": float(np.median(ratio)),
        "p16": float(np.percentile(ratio, 16)),
        "p84": float(np.percentile(ratio, 84)),
        "min": float(np.min(ratio)),
        "max": float(np.max(ratio)),
        "fraction_outside_10_percent": float(np.mean(np.abs(ratio - 1) > 0.1)),
    }


def validate(config, output):
    output.mkdir(parents=True, exist_ok=True)
    bsel_cache_path = output / "bsel_ls_cache.json"
    bsel_signature = _bsel_cache_signature(config)
    bsel_cache = _load_bsel_cache(bsel_cache_path, bsel_signature)
    hod_counts, hod_bias = _selection_counts(config, bsel_cache)
    _save_bsel_cache(bsel_cache_path, bsel_signature, bsel_cache)
    nblocks = len(Z_BINS) * len(LAMBDA_BINS)
    nrad = 15
    hod_covariance = np.zeros((nblocks * nrad, nblocks * nrad))
    control_covariance = np.zeros_like(hod_covariance)
    reference_covariance = np.zeros_like(hod_covariance)
    hod_radii = []
    reference_radii = []
    labels = []
    records = []

    for iz, zbin in enumerate(Z_BINS):
        for ilam, lbin in enumerate(LAMBDA_BINS):
            block = iz * len(LAMBDA_BINS) + ilam
            sl = slice(block * nrad, (block + 1) * nrad)
            reference = _reference_block(zbin, lbin)
            reference_covariance[sl, sl] = reference["covariance"]

            r_hod, hod_block = _covariance(
                config, hod_counts[iz, ilam], hod_bias[iz, ilam], zbin, lbin
            )
            r_control, control_block = _covariance(
                config, reference["counts"], reference["bias"], zbin, lbin
            )
            if not np.allclose(r_hod * config["cosmology"]["h"],
                               reference["r_hmpc"], rtol=1e-5, atol=2e-8):
                raise ValueError(f"radial grid mismatch in z={zbin}, lambda={lbin}")
            hod_covariance[sl, sl] = hod_block
            control_covariance[sl, sl] = control_block
            hod_radii.append(r_hod)
            reference_radii.append(reference["r_hmpc"])
            labels.append(f"z{iz}_lambda{ilam}")
            hod_ratio = np.sqrt(np.diag(hod_block) /
                                np.diag(reference["covariance"]))
            control_ratio = np.sqrt(np.diag(control_block) /
                                    np.diag(reference["covariance"]))
            hod_control_ratio = np.sqrt(np.diag(hod_block) /
                                        np.diag(control_block))
            records.append({
                "z": list(zbin),
                "lambda": list(lbin),
                "hod_counts": float(hod_counts[iz, ilam]),
                "hod_bias": float(hod_bias[iz, ilam]),
                "to21_counts": reference["counts"],
                "to21_bias": reference["bias"],
                "hod_vs_to21": _ratio_summary(hod_ratio),
                "control_vs_to21": _ratio_summary(control_ratio),
                "hod_vs_control": _ratio_summary(hod_control_ratio),
            })

    hod_error_ratio = np.sqrt(np.diag(hod_covariance) /
                              np.diag(reference_covariance))
    control_error_ratio = np.sqrt(np.diag(control_covariance) /
                                  np.diag(reference_covariance))
    hod_control_error_ratio = np.sqrt(np.diag(hod_covariance) /
                                      np.diag(control_covariance))
    summary = {
        "reference": str(REFERENCE),
        "redshift_bins": [list(item) for item in Z_BINS],
        "richness_bins": [list(item) for item in LAMBDA_BINS],
        "radial_bins": 15,
        "covariance_convention": "archived To21 DeltaSigma_cov_combined = raw covariance / h^2",
        "source_distribution": "current DES-Y1 whale approximation; archived source tables are not present locally",
        "selection": "RichnessSelection MOR plus observed-richness K_i projection; hard redshift-bin top-hat",
        "large_scale_selection_bias": {
            "applied": True,
            "definition": "RichnessSelection TwoHalo.b_sel_ls(lob, z) = b_eff(1 + delta_prj), marginalized over latent richness",
            "evaluation": "representative observed richness midpoint; lambda>=1000 uses lob=80; redshift midpoint",
        },
        "bsel_cache": {
            "path": str(bsel_cache_path),
            "signature": bsel_signature,
            "n_cached_values": len(bsel_cache),
        },
        "hod_parameters": HOD_PARAMETERS,
        "hod_vs_to21": _ratio_summary(hod_error_ratio),
        "control_same_counts_bias_vs_to21": _ratio_summary(control_error_ratio),
        "hod_vs_control_same_covariance_engine": _ratio_summary(hod_control_error_ratio),
        "per_bin": records,
    }
    np.savez_compressed(
        output / "covariances.npz",
        hod_covariance=hod_covariance,
        control_covariance=control_covariance,
        reference_covariance=reference_covariance,
        hod_counts=hod_counts,
        hod_bias=hod_bias,
        block_labels=np.asarray(labels),
        hod_radii=np.asarray(hod_radii),
        reference_radii_hmpc=np.asarray(reference_radii),
    )
    (output / "summary.json").write_text(json.dumps(summary, indent=2),
                                          encoding="utf-8")

    fig, axes = plt.subplots(1, 2, figsize=(13, 5), constrained_layout=True)
    for iz, zbin in enumerate(Z_BINS):
        for ilam, lbin in enumerate(LAMBDA_BINS):
            block = iz * len(LAMBDA_BINS) + ilam
            sl = slice(block * nrad, (block + 1) * nrad)
            label = f"z{zbin[0]:.2f}–{zbin[1]:.2f}, λ{lbin[0]}–{lbin[1]}"
            if iz == 0:
                axes[0].loglog(hod_radii[block] * config["cosmology"]["h"],
                               np.sqrt(np.diag(hod_covariance[sl, sl])),
                               alpha=0.5, label=label)
            else:
                axes[0].loglog(hod_radii[block] * config["cosmology"]["h"],
                               np.sqrt(np.diag(hod_covariance[sl, sl])),
                               alpha=0.5)
            axes[1].semilogx(reference_radii[block],
                             np.sqrt(np.diag(hod_covariance[sl, sl]) /
                                     np.diag(reference_covariance[sl, sl])),
                             alpha=0.6)
    axes[0].set_xlabel(r"$R$ [Mpc/h]")
    axes[0].set_ylabel(r"$sigma(\Delta\Sigma)$ [archived To21 units]")
    axes[0].set_title("HOD selection covariance")
    axes[0].legend(fontsize=6, ncol=2, frameon=False)
    axes[1].axhspan(0.9, 1.1, color="0.88")
    axes[1].axhline(1.0, color="k", lw=0.8)
    axes[1].set_xlabel(r"$R$ [Mpc/h]")
    axes[1].set_ylabel(r"HOD / To21 $\sigma$")
    axes[1].set_title("HOD versus archived To21 covariance")
    fig.savefig(output / "hod_vs_to21.png", dpi=180)
    fig.savefig(output / "hod_vs_to21.pdf")
    plt.close(fig)
    return summary


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path,
                        default=ROOT / "configs" / "des_y1.json")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "results" / "desy1_hod_vs_to21")
    args = parser.parse_args()
    config_path = args.config if args.config.is_absolute() else ROOT / args.config
    output = args.output if args.output.is_absolute() else ROOT / args.output
    with config_path.open(encoding="utf-8") as stream:
        config = json.load(stream)
    print(json.dumps(validate(config, output), indent=2))


if __name__ == "__main__":
    main()
